export const COLORS = {
  primary: "#2563eb",
  accent: "#0ea5e9",
  success: "#16a34a",
  danger: "#dc2626",
  background: "#f8fafc",
  surface: "#ffffff",
  textMain: "#0f172a",
  textSec: "#64748b",
  border: "#e2e8f0",
  muted: "#f1f5f9",
};

export const STYLES = {
  layout: {
    minHeight: "100vh",
    width: "100%",
    backgroundColor: COLORS.background,
    fontFamily: "'Rubik', 'Assistant', 'Heebo', Arial, sans-serif",
    display: "flex",
    flexDirection: "column",
    direction: "rtl",
  },
  navbar: {
    width: "100%",
    height: "70px",
    backgroundColor: COLORS.surface,
    borderBottom: `1px solid ${COLORS.border}`,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "0 2rem",
    boxSizing: "border-box",
    position: "sticky",
    top: 0,
    zIndex: 100,
  },
  mainContent: {
    flex: 1,
    padding: "2rem 3rem",
    width: "100%",
    maxWidth: "none",
    margin: 0,
    boxSizing: "border-box",
  },
  gridContainer: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(300px, 1fr))",
    gap: "1.5rem",
    marginTop: "1.5rem",
  },
  card: {
    backgroundColor: COLORS.surface,
    borderRadius: "12px",
    border: `1px solid ${COLORS.border}`,
    padding: "1.5rem",
    boxShadow: "0 4px 6px -1px rgba(0, 0, 0, 0.05)",
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
  },
  btn: {
    padding: "0.75rem 1.5rem",
    borderRadius: "8px",
    border: "none",
    cursor: "pointer",
    fontWeight: "600",
    fontSize: "0.95rem",
    transition: "all 0.2s",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "0.5rem",
  },
  input: {
    padding: "0.75rem",
    borderRadius: "8px",
    border: `1px solid ${COLORS.border}`,
    width: "100%",
    fontSize: "1rem",
    outline: "none",
    backgroundColor: "#f1f5f9",
  },
  modalOverlay: {
    position: "fixed",
    inset: 0,
    backgroundColor: "rgba(15, 23, 42, 0.6)",
    backdropFilter: "blur(4px)",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 1000,
  },
  modalContent: {
    backgroundColor: COLORS.surface,
    padding: "2.5rem",
    borderRadius: "16px",
    width: "90%",
    maxWidth: "500px",
    boxShadow: "0 20px 25px -5px rgba(0, 0, 0, 0.1)",
  },
};
